apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1 
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: image-storage
          persistentVolumeClaim:
            claimName: image-storage
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: "/usr/share/nginx/html"
            name: image-storage
      - image: opensuse/leap
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo echo $(date -u) 'Hi'; sleep 10 ;done"]
        name: sidecar-container
        volumeMounts:
          - mountPath: "/mnt/"
            name: image-storage

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-storage
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
#  storageClassName: longhorn     # Disabled to allow for deployment based on the default storage class
  resources:
    requests:
      storage: 40Gi

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer
  loadBalancerIP: 172.16.240.65
